
"use client"
import { Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import { ReactNode } from "react";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { Provider } from 'react-redux'
import { store } from "./_redux/store";
import { Toaster } from "react-hot-toast";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//we cannot use meta data here because it became a client component

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: roboto.style.fontFamily }}>
     <Provider store={store}>
     <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <Navbar />
            <Box sx={{ marginTop: "2rem",minHeight:"100vh" }}>
              {children}
              <Toaster/>
            </Box>
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
     </Provider>
      </body>
    </html>
  );
}
